"use client";

import Link from "next/link";
import { useState } from "react";

const tracks = {
  company: {label:"Empresa", process:"Pedidos", pack:"Pedidos", caseColumn:"pedido_id", objective:"Reduzir o tempo entre recebimento e aprovação de pedidos.", question:"O intervalo observado entre essas etapas corresponde ao que acontece na operação?", files:"/examples/sync/orders-sync"},
  school: {label:"Escola", process:"Matrículas", pack:"Matrículas", caseColumn:"matricula_id", objective:"Reduzir o tempo entre inscrição e aprovação da documentação.", question:"As pendências de documentação explicam o intervalo observado entre essas etapas?", files:"/examples/pilot/enrollment-sync"},
};

export function PilotGuide() {
  const [sector, setSector] = useState<keyof typeof tracks>("company");
  const track = tracks[sector];
  return <div className="result-stack">
    <header className="page-header"><div><span className="eyebrow">Primeiro piloto</span><h1>Um processo. Uma melhoria verificável.</h1><p>Comece com dados conhecidos, confirme o diagnóstico com sua equipe e acompanhe uma mudança de cada vez.</p></div><Link className="button secondary" href="/">Início</Link></header>
    <section className="panel"><h2>Escolha o ponto de partida</h2><div className="actions" role="group" aria-label="Contexto do piloto">{Object.entries(tracks).map(([key, value]) => <button className={`button ${sector === key ? "" : "secondary"}`} type="button" aria-pressed={sector === key} key={key} onClick={() => setSector(key as keyof typeof tracks)}>{value.label}</button>)}</div><h3>{track.process}</h3><p>{track.objective}</p><p>Defina um responsável pelo processo, um período de observação e uma meta de tempo antes de começar. Os arquivos abaixo são fictícios e servem para experimentar o fluxo.</p><div className="actions"><a className="button secondary" href={`${track.files}-01.csv`} download>Baixar primeira exportação</a><a className="button secondary" href={`${track.files}-02.csv`} download>Baixar segunda exportação</a><Link className="text-link" href="/demo/sync">Experimentar sincronização sem conta</Link></div></section>
    <section className="panel"><h2>Prepare a exportação</h2><p>Uma linha representa um evento do processo. Um mesmo caso pode aparecer em várias linhas, uma por etapa.</p><dl className="sync-review"><dt>Evento</dt><dd><code>event_id</code> identifica o mesmo evento nas próximas exportações. Uma correção mantém esse ID.</dd><dt>Caso</dt><dd><code>{track.caseColumn}</code> reúne as etapas de um pedido ou matrícula.</dd><dt>Atividade</dt><dd><code>etapa</code> descreve o que aconteceu.</dd><dt>Data e hora</dt><dd><code>data_evento</code> informa quando aconteceu, incluindo o fuso horário.</dd><dt>Responsável</dt><dd><code>responsavel</code> é opcional; nos exemplos usamos equipes fictícias.</dd></dl></section>
    <section className="panel"><h2>Faça o primeiro ciclo</h2><ol className="pilot-checklist"><li><strong>Crie seu processo.</strong> Entre na conta, abra a importação, escolha o contexto {track.pack}, selecione Novo processo e use a primeira exportação. Confirme o mapeamento e valide os dados.</li><li><strong>Conecte a fonte recorrente.</strong> No Explorer, abra Conectores e escolha CSV recorrente. Envie o primeiro arquivo, confirme o mapeamento e selecione ID único da fonte com a coluna event_id.</li><li><strong>Comprove a atualização.</strong> Envie a segunda exportação pelo botão Sincronizar novamente. Nos exemplos, ela deve registrar 20 novos, 3 atualizados e 100 duplicados; o conjunto vivo terá 120 eventos.</li><li><strong>Comprove o reenvio.</strong> Envie novamente o segundo arquivo. O total deve continuar em 120 eventos, sem novas alterações ou análise.</li><li><strong>Valide o diagnóstico.</strong> Abra o Explorer e confira o gargalo com quem executa o processo. Pergunta para a equipe: {track.question} Um intervalo observado não comprova sozinho a causa do atraso.</li><li><strong>Simule e acompanhe.</strong> Use Simular melhoria para comparar uma hipótese. Registre a ação escolhida e seu responsável fora do aplicativo; após aplicá-la, envie dados do novo período e compare tempo de ciclo, atrasos e retrabalho. A simulação é uma estimativa, não uma promessa de resultado.</li></ol><div className="actions"><Link className="button" href="/processes/new">Começar meu piloto</Link><Link className="button secondary" href="/auth?mode=signup">Criar conta</Link></div></section>
    <section className="panel"><h2>Quando considerar o piloto validado?</h2><p>A equipe consegue configurar a fonte, interpretar os estados, confirmar os eventos e avaliar uma melhoria sem ajuda em cada etapa. Registre dúvidas e falhas de uso junto com as métricas; testes técnicos e validação operacional têm papéis diferentes.</p><p>Hoje, o envio é manual e requer Owner/Admin. Analyst e Viewer podem consultar os dados conforme as permissões da organização. Se uma coluna configurada desaparecer, restaure a estrutura da exportação e tente novamente; os eventos anteriores são preservados.</p></section>
  </div>;
}
